### ISSUE TITLE
graph failures

### ISSUE THREAD

**Issue by MargareeMan** [kjhealy/covdata#1]
the log-linear graph of cumulative reported cases code fails for me on the following error:

Error in geom_text_repel(nudge_x = 0.75, segment.color = NA) : 
  could not find function "geom_text_repel"

And the fails on:

Error in state %nin% top_n_states(covus) : 
  could not find function "%nin%"

log-linear graph of cumulative reported US cases

It maybe my setup; but I thought I would pass this along.

**Comment by kjhealy** [comment]
Whoops, this happens for the code in the README because I didn't explicitly load some additional libraries I use there. These include `ggrepel` (for the `geom_text_repel()` function), and also `paletteer` and `prismatic` (for the color palette). I've added those explicitly in the `README` example, along with the `%nin%` operator. So assuming you have those libraries installed it should run as written now. Thanks for pointing it out.

**Comment by homerhanumat** [comment]
Yes, it works now.  (I got `%nin%` from package **Hmisc**.)  Thanks, very useful package for my students.

**Comment by kjhealy** [comment]
The new code is already in the repository, and will be shown on the package homepage as soon as GitHub Actions stops being broken this morning and I can rebuild the pages.
