### ISSUE TITLE
remotes::install_github("kjhealy/covdata") defaults to branch master, not main

### ISSUE THREAD

**Issue by chirila** [kjhealy/covdata#11]
When I install from 
remotes::install_github("kjhealy/covdata"), it gives the message
Downloading GitHub repo kjhealy/covdata@master
and installs covdata 0.4.0.
However, the most recent branch appears to be "main", at version 0.5.4, according to https://kjhealy.github.io/covdata/articles/covdata.html

**Comment by kjhealy** [comment]
This is because `remotes::install_github("kjhealy/covdata")` is installing from the `master` branch but development is happening on `main`. This will get you the current version:

`remotes::install_github("kjhealy/covdata@main")`

Sorry for the confusion. (I'd forgotten `install_github()` would do this.) I'll update the README to make the instructions clear.
