### ISSUE TITLE
Problems with reading a csv file

### ISSUE THREAD

**Issue by JoseMontoya518** [kjhealy/covdata#5]
Hi , I was trying to use your useful code but I can't read a csv file : This is your following code:

```
 statefips <- read_csv(here("data-raw/data/state_fips_master.csv")) %>%   select(state_name, state_abbr, region_name, division_name) %>%
rename(state = state_name)
```

```
uspop <- read_csv(here("data-raw/data/PEP_2018_PEPSR6H_with_ann.csv")) %>%
  janitor::clean_names() %>%
  filter(estimate == "est72018", !is.na(statefips)) %>%
  select(sex_id:tom) %>%
  left_join(statefips) %>%
  select(state, state_abbr, statefips, region_name, division_name, everything())

```

And I get these error messages:
`Error: `file` must be a string, raw vector or a connection.`

Also when I checked this 
```
## Check for data/ dir in data-raw
ifelse(!dir.exists(here("data-raw/data")),
       dir.create(file.path("data-raw/data")),
       FALSE)
```
I get this error :`Error in dir.exists(here("data-raw/data")) : invalid filename argument`

Can you give an example of how to load those files? Thank you in advance. Your work is awesome! :)

**Comment by kjhealy** [comment]
Hi Jose, 

This code loads some csv files as part of the data prep/cleaning process for the package. It's not meant to be run by the user. The csv files aren't included in the package for that reason. The `state_fips_master.csv` file can be found at https://github.com/kjhealy/fips-codes. The `PEP_2018_PEPSR6H_with_ann.csv` file is from the US Census population estimates for 2018. As I say these files aren't included in the repo because they're not part of the package.

Kieran

**Comment by JoseMontoya518** [comment]
I get it. I found the file from the US Census population estimates for 2018(https://raw.githubusercontent.com/JoseMontoya518/uspop2018/master/PEP_2018_PEPSR6H_with_ann.csv). I've already uploaded to my repository. But there is a problem with this code:

```
uspop <- read_csv(here("data-raw/data/PEP_2018_PEPSR6H_with_ann.csv")) %>%
  janitor::clean_names() %>%
  filter(estimate == "est72018", !is.na(statefips)) %>%
  select(sex_id:tom) %>%
  left_join(statefips) %>%
  select(state, state_abbr, statefips, region_name, division_name, everything())
```
When I try to filter the data, there is a problem with this input: `!is.na(statefips)`

```
Error: Problem with `filter()` input `..2`.
x Input `..2` must be of size 5149 or 1, not size 50.
i Input `..2` is `!is.na(statefips)`.
```
statefips object size is 50.

In addition there's   another issue here:
```
left_join(statefips) %>%
  select(state, state_abbr, statefips, region_name, division_name, everything())
```
```
Error: `by` must be supplied when `x` and `y` have no common variables.
i use by = character()` to perform a cross-join
```
there should be a criterion to join both dataframes and there is not.
Do you have any suggestions to modify the code so that it works correctly?
Thank you in advance!

**Comment by kjhealy** [comment]
This is because I modified the Census PEP so that I could properly merge it (adding a `statefips` column). I've added the `state_fips_master.csv` and `PEP_2018_PEPSRR6H_with_ann.csv` files to the repo, so use these versions and things should work. Again, unlike the actual package code in the repo, which you can clone and build cleanly in R, etc, you should not expect code in the `data-raw` part of the repo to just run, as it's not part of the package.
